[package]
name = "pippo"
version = "0.0.1-SNAPSHOT"
authors = ["Nico Bellack", "Tobias Richter", "Benjamin Sommerfeld"]
description = "Rust-powered tool to communicate with Adobe Cloud Manager"
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/wcm-io-devops/pippo"
repository = "https://github.com/wcm-io-devops/pippo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-ctrlc = "1.2.0"
async-trait = "0.1.52"
cargo-edit = "0.12.3"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "3.2.4", features = ["derive", "yaml", "env"] }
colored = "2.1.0"
env_logger = "0.10.0"
flate2 = "1.0.33"
futures-lite = "2.3.0"
jsonwebtoken = "8.3.0"
log = "0.4.17"
magic-crypt = "3.1.13"
num = "0.4.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
serde_yaml = "0.8.21"
strum = "0.23.0"
strum_macros = "0.26.4"
tokio = { version = "1.29.1", features = ["full"] }
headers = "0.4.0"
[dependencies.reqwest]
version = "0.11.6"
#default-features = false
features = ["json", "rustls-tls"]

[dependencies.uuid]
version = "1.10.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[package.metadata.cross.target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install --assume-yes libssl-dev"
]

[target.x86_64-apple-darwin.dependencies]
openssl = { version = "0.10", features = ["vendored"] }


